import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import Footer from "../components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-background`}
    >
        <body className="items-center h-dvh overflow-hidden lg:h-auto lg:min-h-full lg:overflow-visible flex flex-col bg-background">
            <Header />
            <main className="flex flex-1 min-h-0 w-full items-center-safe justify-center-safe overflow-y-auto lg:items-center lg:justify-center lg:overflow-visible lg:min-h-auto">
                {children}
            </main>
            <Footer />
        </body>
    </html>
  );
}
